# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_auto_20160421_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_users',
            name='holidays',
            field=models.DateField(default='2016-04-21'),
        ),
    ]
